#include <bits/stdc++.h>
using namespace std;

// Generated by ChatGPT4
vector<int> buildSuffixArray(const string& s) {
    int n = s.size();
    vector<pair<string, int>> suffixes;

    for (int i = 0; i < n; i++) {
        suffixes.push_back({s.substr(i), i});
    }

    sort(suffixes.begin(), suffixes.end());

    vector<int> sa;
    for (auto& p : suffixes) {
        sa.push_back(p.second);
    }

    return sa;
}

int main() {
    string s = "banana";
    vector<int> sa = buildSuffixArray(s);

    for (int i : sa) cout << i << " ";

    int biscuits[5]{20, 54, 43, 54};

    cout << "\n\nPrinting biscuit\n\n";
    for(auto s : biscuits) {
        cout << s << "newline\n";
    }
}